USE Examen;

-- Tranzactia 1 Deadlock
-- SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
-- SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
-- SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
-- SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
-- SET DEADLOCK_PRIORITY HIGH;
BEGIN TRANSACTION A;
UPDATE Tablouri SET Nume = 'TablouUpdatat' WHERE Id = 1;
WAITFOR DELAY '00:00:05'
UPDATE Tipuri SET Nume = 'TitluUpdatat' WHERE Id = 1;
COMMIT TRANSACTION A;

-- Tranzactia 1 Deadlock Evitare
BEGIN TRANSACTION B;
UPDATE Tipuri SET Nume = 'TitluUpdatat' WHERE Id = 1;
WAITFOR DELAY '00:00:03'
UPDATE Tablouri SET Nume = 'TablouModificat' WHERE Id = 1;
COMMIT TRANSACTION B;

SELECT * FROM Tablouri;
SELECT * FROM Tipuri;