package app.network.jsonprotocol;

public enum RequestType {
    LOGIN, FIND_PLAYER_BY_ALIAS, GET_ALL_WORDS, GET_ALL_GAMES, GET_ALL_CONFIGURATIONS, ADD_GAME, ADD_POSITION, ADD_CONFIGURATION, ADD_CONFIGURATION_WORD, LOGOUT;
}
